{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "letta.fullname" . }}-nginx-config
  labels:
    {{- include "letta.nginx.labels" . | nindent 4 }}
data:
  nginx.conf: |
    events {
    }
    http {
        map $http_upgrade $connection_upgrade {
            default upgrade;
            ''      close;
        }
        server {
            listen 80;
            listen [::]:80;
            listen 8283;
            listen [::]:8283;
            server_name letta.localhost;
            set $api_target "http://{{ include "letta.fullname" . }}-server:8283";
            location / {
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_http_version 1.1;
                resolver 127.0.0.11;
                proxy_pass $api_target;
            }
        }
        server {
            listen 80 default_server;
            server_name not_found;
            return 404;
        }
    }
{{- end }}

