name: Promote E2B from staging to production

on:
  workflow_dispatch:
    inputs:
      template_id:
        description: 'Template ID to deploy'
        required: false
        type: string

jobs:
  promote-template-id:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    # TODO: refactor this eventually to promote to prod_e2b_E2B_SANDBOX_TEMPLATE_ID.
    # but first we have to land kian/secrets-part-2 which will deploy prod secrets
    - name: Promote Template ID
      run: |
        if [ -n "${{ inputs.template_id }}" ]; then
          template_id="${{ inputs.template_id }}"
          echo "Using provided template ID: $template_id"
        else
          template_id=$(gcloud secrets versions access latest --secret dev_e2b_E2B_SANDBOX_TEMPLATE_ID)
          echo "Using template ID from dev_e2b_E2B_SANDBOX_TEMPLATE_ID secret"
        fi
        template_id=$(echo "$template_id" | tr -d '\n\r ')
        echo "$template_id" | gcloud secrets versions add dev_ci_E2B_SANDBOX_TEMPLATE_ID --data-file=-

    - name: Fire alert
      if: failure()
      run: just alert "${{ github.workflow }} failed!" "${{ github.actor }}"
