name: ðŸŒ¿ Publish Docs

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: [self-hosted, medium]
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/heads/main') && github.run_number > 1 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Docs
        working-directory: apps
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --docs --log-level debug
