name: üï∏Ô∏èüß™ [Web] Lint and Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: changed-files
    outputs:
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            apps/web/**
            apps/cloud-api/**
            apps/desktop-ui/**
            apps/desktop-electron/**
            apps/lettuce/**
            libs/ui-component-library/**
            libs/ui-ade-components/**
            libs/ui-styles/**
            libs/sdk-web/**
            libs/service-database/**
            libs/service-email/**
            libs/service-feature-flags/**
            libs/service-payments/**
            libs/service-rbac/**
            libs/service-redis/**
            libs/sdk-lettuce/**
            libs/types/**
            libs/utils-client/**
            libs/utils-server/**
            libs/utils-shared/**
            libs/service-analytics/**
            libs/config-agent-starter-kits/**
            libs/service-auth/**
            .github/workflows/web-tests.yml
  main:
    env:
      CLOUD_API_ENDPOINT: http://localhost:3006
    needs: [ changed-files ]
    if: ${{ needs.changed-files.outputs.any_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: ‚éî Setup node
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: ./package.json
          node-version-file: '.nvmrc'
      - run: npm ci --legacy-peer-deps
      - run: npm run web:lint
      - run: npm run web:test
